version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"

  kafka1:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "20000"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "input:60:1"

  kafka2:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zookeeper
    ports:
      - "19092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 19092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "20000"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "input:30:2"

  kafka3:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zookeeper
    ports:
      - "29092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_PORT: 29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "20000"
      KAFKA_CREATE_TOPICS: "input:15:1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  timescaledb:
    image: timescale/timescaledb:1.7.2-pg12-oss
    ports:
      - "5432:5432"
    command: "-p 5432"
    environment:
      POSTGRES_PASSWORD: "password"
      TS_TUNE_MEMORY: 8GB

  jobmanager:
    image: flink-timescale:latest
    expose:
      - "6123"
    ports:
      - "8081:8081"
    depends_on:
      - kafka1
    environment:
      JOB_MANAGER_RPC_ADDRESS: "jobmanager"
      command: "jobmanager"

  taskmanager:
    image: flink-timescale:latest
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: "jobmanager"
      TASK_MANAGER_NUMBER_OF_TASK_SLOTS: 15
      command: "taskmanager"
      TASK_MANAGER_HEAP_SIZE: 16384m

  flink-timescale:
    image: flink-timescale:latest
    depends_on:
      - kafka1
#      - kafka2
#      - kafka3
      - timescaledb
      - taskmanager
    ports:
      - "5005:5005"
    environment:
      TOPIC_SOURCE: "input"
      BOOTSTRAP_SERVER: "kafka1:9092"
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "password"
      POSTGRES_URL: "jdbc:postgresql://192.168.2.187:5432/postgres?reWriteBatchedInserts=false"
      JOB_NAME: "flink-timescale"
      JOB_MANAGER_RPC_ADDRESS: "jobmanager"
      command: "startJob"
      JOB_MANAGER_REST_PORT: 8081
      JOB_MANAGER_RPC_PORT: 6123
      JOB_MANAGER_BLOB_PORT: 6124
      JOB_MANAGER_QUERY_PORT: 6125
      PARALLELISM: 15
      MAIN_CLASS: "com.flink.timescale.Application"
      NUM_STREAM_THREADS: 1
      JAR_FILE_NAME: "job.jar"
