version: '3'

services:

  zookeeper:
    image: bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "true"

  kafka1:
    image: bitnami/kafka:3
    container_name: kafka1
    ports:
      - "9093:9093"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "true"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka1:9092,EXTERNAL://192.168.2.138:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  kafka2:
    image: bitnami/kafka:3
    container_name: kafka2
    ports:
      - "9094:9094"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "true"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka2:9092,EXTERNAL://192.168.2.138:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  kafka3:
    image: bitnami/kafka:3
    container_name: kafka3
    ports:
      - "9095:9095"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "true"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9095
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka3:9092,EXTERNAL://192.168.2.138:9095
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  timescaledb:
    image: timescale/timescaledb:2.5.0-pg14
    ports:
      - "5432:5432"
    command: "-p 5432"
    environment:
      POSTGRES_PASSWORD: "password"
      TS_TUNE_MEMORY: 16GB

  jobmanager:
    image: flink-timescale:latest
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      JOB_MANAGER_RPC_ADDRESS: "jobmanager"
      command: "jobmanager"

  taskmanager:
    image: flink-timescale:latest
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: "jobmanager"
      TASK_MANAGER_NUMBER_OF_TASK_SLOTS: 45
      command: "taskmanager"
      TASK_MANAGER_PROCESS_SIZE: 16384m


  flink-timescale:
    image: flink-timescale:latest
    ports:
      - "5005:5005"
    environment:
      CRIMES_JAR_FILE_NAME: "crimes.jar"
      CRIMES_MAIN_CLASS: "com.flink.Application"
      CRIMES_PARALLELISM: 1
      CRIMES_REPLICATION: 1
      CRIMES_SOURCE: "input"
      LOGS_JAR_FILE_NAME: "logs.jar"
      LOGS_MAIN_CLASS: "com.flink.logs.Application"
      LOGS_PARALLELISM: 60
      LOGS_REPLICATION: 1
      LOGS_SOURCE: "logs"
      BOOTSTRAP_SERVER: "192.168.2.138:9093"
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "password"
      POSTGRES_URL: "jdbc:postgresql://192.168.2.138:5432/postgres?reWriteBatchedInserts=true"
      JOB_NAME: "flink-timescale"
      JOB_MANAGER_RPC_ADDRESS: "jobmanager"
      command: "startJob"
      JOB_MANAGER_REST_PORT: 8081
      JOB_MANAGER_RPC_PORT: 6123
      JOB_MANAGER_BLOB_PORT: 6124
      JOB_MANAGER_QUERY_PORT: 6125
